FROM jupyter/base-notebook

WORKDIR /app

# Copy the pip_env.sh file
COPY pip_env.sh /app/pip_env.sh
COPY data /app/data

# Run the pip_env.sh script to install dependencies
RUN bash pip_env.sh



# Copy the fakenews_detection.ipynb file
COPY fakenews_detectionfinal.ipynb /app/fakenews_detectionfinal.ipynb

EXPOSE 8888

CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--no-browser", "--allow-root"]
